apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: metakube-provider-secret
type: Opaque
data:
  credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: metakube.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: metakube-example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: metakube-provider-secret
      key: credentials
